(in-package :cl-info)
(let (
(deffn-defvr-pairs '(
; CONTENT: (<INDEX TOPIC> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS> <NODE NAME>))
("DST" . ("equation_of_time.info" 2547 82 "Definitions for equation_of_time"))
("E" . ("equation_of_time.info" 3595 50 "Definitions for equation_of_time"))
("LT" . ("equation_of_time.info" 4036 64 "Definitions for equation_of_time"))
("T" . ("equation_of_time.info" 4256 58 "Definitions for equation_of_time"))
("UT" . ("equation_of_time.info" 4412 47 "Definitions for equation_of_time"))
("UT_to_local_time" . ("equation_of_time.info" 2630 102 "Definitions for equation_of_time"))
("analemma" . ("equation_of_time.info" 1749 118 "Definitions for equation_of_time"))
("calculate_rise_time" . ("equation_of_time.info" 2058 160 "Definitions for equation_of_time"))
("day" . ("equation_of_time.info" 3416 37 "Definitions for equation_of_time"))
("day_duration" . ("equation_of_time.info" 2836 118 "Definitions for equation_of_time"))
("day_of_year" . ("equation_of_time.info" 2454 92 "Definitions for equation_of_time"))
("dec" . ("equation_of_time.info" 3454 47 "Definitions for equation_of_time"))
("dow" . ("equation_of_time.info" 3502 36 "Definitions for equation_of_time"))
("ds" . ("equation_of_time.info" 3539 55 "Definitions for equation_of_time"))
("equation_of_time" . ("equation_of_time.info" 1648 100 "Definitions for equation_of_time"))
("equation_of_time_full" . ("equation_of_time.info" 1508 139 "Definitions for equation_of_time"))
("gha" . ("equation_of_time.info" 3646 56 "Definitions for equation_of_time"))
("greenwich_hour_angle" . ("equation_of_time.info" 1868 96 "Definitions for equation_of_time"))
("h" . ("equation_of_time.info" 3703 69 "Definitions for equation_of_time"))
("hour_angle" . ("equation_of_time.info" 3773 53 "Definitions for equation_of_time"))
("jd" . ("equation_of_time.info" 3827 41 "Definitions for equation_of_time"))
("julian_dow" . ("equation_of_time.info" 2219 234 "Definitions for equation_of_time"))
("lambda" . ("equation_of_time.info" 3869 57 "Definitions for equation_of_time"))
("lat" . ("equation_of_time.info" 3927 53 "Definitions for equation_of_time"))
("local_to_UT_time" . ("equation_of_time.info" 2733 102 "Definitions for equation_of_time"))
("lon" . ("equation_of_time.info" 3981 54 "Definitions for equation_of_time"))
("month" . ("equation_of_time.info" 4101 40 "Definitions for equation_of_time"))
("observer_coord" . ("equation_of_time.info" 2955 163 "Definitions for equation_of_time"))
("observer_coord_gha" . ("equation_of_time.info" 3119 176 "Definitions for equation_of_time"))
("phi" . ("equation_of_time.info" 4142 53 "Definitions for equation_of_time"))
("sgn" . ("equation_of_time.info" 4196 59 "Definitions for equation_of_time"))
("sun_alt_az" . ("equation_of_time.info" 3296 119 "Definitions for equation_of_time"))
("sun_hour_angle" . ("equation_of_time.info" 1965 92 "Definitions for equation_of_time"))
("tz" . ("equation_of_time.info" 4315 48 "Definitions for equation_of_time"))
("tzi" . ("equation_of_time.info" 4364 47 "Definitions for equation_of_time"))
("week" . ("equation_of_time.info" 4460 39 "Definitions for equation_of_time"))
("year" . ("equation_of_time.info" 4500 52 "Definitions for equation_of_time"))
))
(section-pairs '(
; CONTENT: (<NODE NAME> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS>))
("Definitions for equation_of_time" . ("equation_of_time.info" 1434 3118))
("Introduction to equation_of_time" . ("equation_of_time.info" 528 747))
)))
(load-info-hashtables (maxima::maxima-load-pathname-directory) deffn-defvr-pairs section-pairs))
