(in-package :cl-info)
(let (
(deffn-defvr-pairs '(
; CONTENT: (<INDEX TOPIC> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS> <NODE NAME>))
("E" . ("julian.info" 2447 50 "Definitions for julian"))
("T" . ("julian.info" 2630 76 "Definitions for julian"))
("UT" . ("julian.info" 2707 47 "Definitions for julian"))
("calendar" . ("julian.info" 1779 100 "Definitions for julian"))
("calendar8601" . ("julian.info" 1880 105 "Definitions for julian"))
("centuries_j2000" . ("julian.info" 2102 96 "Definitions for julian"))
("cosd" . ("julian.info" 2276 76 "Definitions for julian"))
("day" . ("julian.info" 2353 45 "Definitions for julian"))
("dec" . ("julian.info" 2399 47 "Definitions for julian"))
("emacs_absolute_day" . ("julian.info" 1986 115 "Definitions for julian"))
("iso8601" . ("julian.info" 1540 238 "Definitions for julian"))
("jd" . ("julian.info" 2498 41 "Definitions for julian"))
("julian" . ("julian.info" 1106 82 "Definitions for julian"))
("julian1900" . ("julian.info" 1328 105 "Definitions for julian"))
("julian1904" . ("julian.info" 1434 105 "Definitions for julian"))
("julianDay" . ("julian.info" 2540 48 "Definitions for julian"))
("modified_julian" . ("julian.info" 1189 138 "Definitions for julian"))
("month" . ("julian.info" 2589 40 "Definitions for julian"))
("sind" . ("julian.info" 2199 76 "Definitions for julian"))
("year" . ("julian.info" 2755 39 "Definitions for julian"))
))
(section-pairs '(
; CONTENT: (<NODE NAME> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS>))
("Definitions for julian" . ("julian.info" 1052 1742))
("Introduction to julian" . ("julian.info" 398 525))
)))
(load-info-hashtables (maxima::maxima-load-pathname-directory) deffn-defvr-pairs section-pairs))
